### ISSUE TITLE
Typescript compile error in data-interface.ts

### ISSUE THREAD

**Issue by icsaszar** [visjs/vis-data#159]
I'm trying to use this along with `vis-network` for a project with typescript, but I keep getting the following error:

https://github.com/visjs/vis-data/blob/5ca23acbdb2d27444e76dee74bebd49f43409f62/src/data-interface.ts#L49

```
node_modules/vis-data/declarations/data-interface.d.ts:33:67 - error TS2304: Cannot find name 'Node'.

33 export declare type DeepPartial<T> = T extends any[] | Function | Node ? T : T extends object ? {
                                                                     ~~~~

```

Removing `Node` seems to fix the issue, but I'm not sure if it won't break something else.

**Comment by Thomaash** [comment]
My guess is that you don't have DOM types installed. Node is the parent type of HTMLElement etc. Removing it would break some type checking (it would no longer be required to be a valid Node, HTMLElement and so on).

**Comment by icsaszar** [comment]
You're right, I used vis-data in a vscode extension and it doesn't import dom by default.

Thanks for the help.

I'll leave a link to a stackoverflow [answer](https://stackoverflow.com/questions/42603783/missing-basic-dom-types-in-typescript-project/42604094) in case anyone else runs into this.
