### ISSUE TITLE
Unmet Peer Dependency

### ISSUE THREAD

**Issue by s4m0r4m4** [visjs/vis-data#175]
I just upgraded to vis-data v6.5.0.

When I run npm install, it displays this warning message:
`npm WARN vis-data@6.5.0 requires a peer of vis-util@^2.1.0 but none is installed. You must install peer dependencies yourself.`

Looking at the package.json of vis-data (v6.5.0), it shows vis-util@^2.1.0 as a peerDependency and vis-util@4.0.0 as a devDependency. My app runs fine if I just use vis-util@4.0.0, but I wanted to see if this is a mistake or if I'm really supposed to have vis-util@^2.1.0 installed to support vis-data@6.5.0.

A similar issue seems to be present in vis-network@7.4.0 (I know they have a different repo, but figured I would mention it here).

Thanks!

**Comment by Thomaash** [comment]
Hi @s4m0r4m4,

this is a bug. You have to have ^4.0.0 for this to work, ^2.1.0 won't work at all. I'll publish a fix.

**Comment by s4m0r4m4** [comment]
Excellent, thanks for the quick response! Do you want me to create a separate issue in the vis-network repo too?
