### ISSUE TITLE
Edge color updating bug.

### ISSUE THREAD

**Issue by baloian** [visjs/vis-data#26]
Hi Everyone,

I am trying to update edges' color by providing an array of edges (every single edge has different color), but it updated all edges' color. But if I update just one edge it works correct, other edges remain the same, if number of updated data is more than one it updates all colors, basically sets the last element's color.

Is this bug or I am not doing it in a right way? 

Here is how I update edge data
`dataSetsObject.update(edges);`

**Comment by Thomaash** [comment]
I'm just supposed to just know what's the content of `edges` by looking into my crystal ball or what?

**Comment by baloian** [comment]
Sorry, I missed to provide it. An `edges` is an array of JSON objects and format of every single object is this (real example)
![Screenshot from 2019-10-11 11-50-42](https://user-images.githubusercontent.com/17729542/66665849-638e7d00-ec1d-11e9-8455-88016cf69c65.png)

**Comment by baloian** [comment]
@Thomaash so the color object's color field is different for every single edge, but as a result I see the latest object's color for all edges instead of different colors. Any recommendations ?

**Comment by Thomaash** [comment]
Hmmm, it doesn't happen to me. Could you tweak the following MWE https://jsfiddle.net/thomaash/ov0nfkw9/ to show your issue, please?

**Comment by baloian** [comment]
Interesting, I do the same but in a big project. I am assigning color object dynamically do you think that it can cause the problem? may be it creates one value and multiple links.

**Comment by Thomaash** [comment]
I don't see how this could happen. But you can simply try `JSON.parse(JSON.stringify(edges))` and see if it makes the issues disappear.

**Comment by baloian** [comment]
I tried but it didn't help. This is really strange because I do update for nodes using the same methods.

**Comment by Thomaash** [comment]
Hmm, could you post `console.log(edges._data)` output (fully unpack at least one edge)?

**Comment by baloian** [comment]
See the result of the `console.log(edges._data)` for one item. Just wanted you to know that colors are different after update operation only here not in UI.
 Also, I can give you access to repo if you wish so you can see how I designed it.

![Screenshot from 2019-10-11 17-21-09](https://user-images.githubusercontent.com/17729542/66685927-d282ca80-ec4b-11e9-8a52-ad466ae1bf14.png)

**Comment by Thomaash** [comment]
Oh, the color values are getters. This could mess things up. Where do these getters get their values?

**Comment by baloian** [comment]
Oops, I do not modify `edge` object after this `dataSets.edges = new vis.DataSet(edges);` operation. Any recommendation how can I debug it and figure it out?

**Comment by Thomaash** [comment]
I would put a break point (or console.log) into the getters to see what's actually going on there.

**Comment by baloian** [comment]
Feel free to see [(link)](https://testmoveh.com/#/NetworkMap) the result at first in console mode where I print edges._object after update operation. Let me know you thoughts please.

**Comment by Thomaash** [comment]
Do you have the whole data set observed by Vue?

**Comment by baloian** [comment]
I don't think so. Do you want me to change the code and you will see whole data set object?

**Comment by Thomaash** [comment]
Actually looking through your source code (VisGraph.vue:65-68) you have it observed. I would try to define it without observing to see if it changes anything.

**Comment by baloian** [comment]
@Thomaash , I am not sure that I got you properly, but I need a value in Vue to keep it kind of global right? as DataSet and update not in the same scope.

**Comment by Thomaash** [comment]
Check https://github.com/rpkilby/vue-nonreactive out. Then you should be able to put `data: Vue.nonreactive({ nodes: [], edges: [] })` into VisGraph.vue:65-68. This should prevent the data sets from being observed and maybe (really not sure here) resolve the issues.

**Comment by baloian** [comment]
Okay, thanks a lot I appreciate it. Let me check it out and will keep you updated. I just wanted you to notice one thing that in the same they everything works for Nodes, and I cannot explain it, on the other side when I do this `edges.update(edge[0])` it works prefect. Problem occures when I am trying to update more than one edges.

**Comment by baloian** [comment]
BTW, when I use the old version of vis.js (version to 4.9.0) it works without any problem.

**Comment by Thomaash** [comment]
And 5.0.0 doesn't work either?

**Comment by baloian** [comment]
Nope

**Comment by baloian** [comment]
@Thomaash I am just wondering why it works perfect in old version, but it doesn't in new version? any thoughts?

**Comment by Thomaash** [comment]
You can try to find out in which version it stopped working. 4.9.0 to 5.0.0 is really big range (those are about 4 years of development).

**Comment by baloian** [comment]
It works for 4.9.0 version, but it doesn't for 5.0.0

**Comment by Thomaash** [comment]
I was talking about the 19 versions in between.

**Comment by baloian** [comment]
Okay, I see what did you mean. Well, I am not sure if I can figure it out in vis library, because I am not so familiar with source code and it may take for a while. Thank you very much! I will try to find some solutions to this, and let me know if you have any recommendations, currently trying `nonreactive` to see if it helps.

**Comment by baloian** [comment]
I tried `nonreactive`, but unfortunately it did not help :(

**Comment by baloian** [comment]
@Thomaash Does this say something to you? screenshot is taken form [documentation](https://visjs.github.io/vis-network/docs/network/)
![edgedoc](https://user-images.githubusercontent.com/17729542/66705471-1251bc80-ecf5-11e9-81ec-ac084b279c13.png)

**Comment by baloian** [comment]
Hi @Thomaash,  just wanted you to know that I solved the issue. So let me provide some details just in case if somebody has the same issue.

1. First of all I use `vis.js` in Vue environment and problem is in `Vue` not in the vis.js library. `Vue` adds proxies to all member variables of all objects. Detailed explanation of this issue you can find [here](https://github.com/almende/vis/issues/2567#issuecomment-307018327).

2. Solution is pretty straightforward.  Move the options and `graph` object out of the data() method of `Vue.js`. See below example:

```
export default{
    data() {
      return { <some_reactive_data> }
    },
    // Static data
    // You can access to this variable like this this.$options.graph in your code.
    graph: null,
}
```

Somewhere in your code you should initialized graph value like this:
`this.$options.graph = new vis.Network(document.querySelector('.graph'), network_data, network_options);  `

More details explanation of the solution you can find [here](https://github.com/almende/vis/issues/2567#issuecomment-307318819).

Thank you very much @Thomaash, you helped me to look the problem in the right direction. I am closing this issue.
