### ISSUE TITLE
[BUG] Update inside forEach not working

### ISSUE THREAD

**Issue by Dignity1337** [visjs/vis-data#382]
Hi. I'm currently facing an unusual behavior while updating the items of a dataset. I'm using the peer build of the vis.js network in combination with the datasets.
My edge objects that I store inside the dataset look like this (an example of one edge):

```
{ 
id: 185, 
from: 75, 
to: 65, 
label: '',
arrows: "to", 
color: "#FA0000", 
communicationtype: "Test", 
communicationcostValue: "1" 
}
```

I have an option (just a checkbox) to display the communicationcostValue at the edges. My solution is simple: I just update all edges. Here is the corresponding code (which causes the issue):

```
function costAtEdges(enable)
{
    if (enable)
    {
        edges.forEach(function(item, id)
        {
            item.label = item.communicationcostValue;
            edges.updateOnly(item);
        });
    } else {
        edges.forEach(function(item, id)
        {
            item.label = ' ';
            edges.updateOnly(item);
        });
    }
}
```

This will end in an endless loop which is eventually terminated by the browser.
I've also tried this (works fine):

```
var test = edges.get(44);
test.label = 'HALLO';
edges.updateOnly(test);
alert(edges.get(44).label);
```

Also using just forEach (without updating) also works fine
So, I assume that there is a problem with updating inside a forEach function.
I didn't try out if the map function of a dataset also causes such an issue.

Have a nice day
- Jannis

**Comment by Thomaash** [comment]
Hi @Dignity1337,

could you provide an MWE, please? Because this seems to work: https://jsfiddle.net/cwrmvkp2/.

Thanks.

**Comment by Dignity1337** [comment]
Thanks to your example I was able to narrow it down to a performance issue. My dataset has about 3000 items. If you open your example and just insert this code after you filled your edges dataset, you can see the issue:

for(var i = 6; i < 2000; i++) {
	edges.add({ 
			id: i, 
			from: 10, 
			to: 20, 
			label: ''
			});
}

Just adding edges from 10 to 20 here so that they are not drawn (would also cause performance issues without the correct network options).

Now after two seconds when your function starts, everything is going to crash.
So it seems as if it's really a performance thing and not really a bug.

**Comment by Thomaash** [comment]
Well, updating all of them in one go instead of one by one would be much faster:
```javascript
  edges.updateOnly(edges.get().map(({
    id
  }) => ({
    id,
    label: "TEST1"
  })))
```
You can also add them one by one into an array in the for each cycle and then use `updateOnly()` to update them all, if the for each is important to you for some reason.

**Comment by Dignity1337** [comment]
Thank you very much. This seems to work. Just one last question:

My function looks like this now:

```
function costAtEdges(enable)
		{
			if(enable)
			{
				edges.updateOnly(edges.map(function(item, id)
				{
					item.label = item.communicationcostValue;
					return item;
				}));
			} else {
				edges.updateOnly(edges.map(function(item, id)
				{
					item.label = "";
					return item;
				}));
			}
			edgesDataView.refresh();
		}
```

Calling this function with parameter true works fine.

However, calling this function whith parameter false does not remove the label. I checked the dataset by logging every item into the console. The label is properly set to "" (empty string ) after calling the function with parameter false but the network does not update and still shows the label.

I noticed that using a space " " instead of "" fixes the issue. However this behavior also occurs in another part of my code and causes issues there.

Thanks for your help so far
- Jannis

**Comment by Thomaash** [comment]
This is because `""` is not a valid label and therefore is ignored. At the moment there is indeed no way to get rid of a label once set (even if you delete the label from the data set, it will be stuck in the network).

**Comment by Dignity1337** [comment]
Ok all right. In this case I'll stick to setting the label to " " and for the other stuff just destroying and restarting the network.
Thanks for your help. I'll now close the issue because it seems to be just a performance issue of my code and not a bug.
