### ISSUE TITLE
[BUG] updateOnly will delete arrows

### ISSUE THREAD

**Issue by Dignity1337** [visjs/vis-data#384]
Hi. After my last issue I faced a funny one.
The updateOnly function of the dataset will remove the arrows property of an object. The update function works fine. This is typically not an issue because the arrows will still get drawn after updating. To really reload the data the network needs to be destroyed and then restarted. So I guess that no one ever noticed this issue.

Here is the code that I used:

```
<!DOCTYPE html>

<html>
	<head>
		<script type="text/javascript" src="https://unpkg.com/vis-data@latest/peer/umd/vis-data.min.js"></script>
		<script type="text/javascript" src="https://unpkg.com/vis-network@latest/peer/umd/vis-network.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://unpkg.com/vis-network/styles/vis-network.min.css" />
	</head>
	<body></body>
</html>

<script type="text/javascript">
var myData = new vis.DataSet([
  { id: 1, from: 1, to: 3, arrows: 'to' },
]);

alert(myData.get(1).arrows);

var item = myData.get(1);
myData.updateOnly(item);

alert(myData.get(1).arrows);
</script>
```

The first alert says "to". The second one "undefined". 

I also logged the entire dataset into the console. The arrows property is simply gone. All other properties are still there.

The update function by the way works fine. If you replace "updateOnly" with "update" inside the code above, the first and second altert says "to" and when logging the entire dataset into console, the arrows property is still there.

Have a nice day
- Jannis

**Comment by Thomaash** [comment]
Hmm, this is really weird. As a workaround you can use `"to to"` instead of `"to"` (enabling the same arrow multiple times shouldn't cause any issues for the time being). However the fact that this works puzzles me even more.

**Comment by Thomaash** [comment]
A fix is awaiting review.
