### ISSUE TITLE
postinstall

### ISSUE THREAD

**Issue by mgobishop** [visjs/vis-data#5]
The most recent postinstall fix is not in vis-data 6.1.0.
The consequence is that when I npm install vis-timeline or vis-network I get the following error:
npm ERR! Failed at the vis-data@6.1.0 postinstall script. 
Help! :-)

**Comment by Thomaash** [comment]
I'm going to look into this.

**Comment by Thomaash** [comment]
@mgobishop If you need a quick and dirty fix: `npm i -D opencollective`.

**Comment by mojoaxel** [comment]
fixed with 31c3a44e0ade9ee2cba88dffd547c6832ae4bc33
