### ISSUE TITLE
Dataset.Max | Dataset.Min not working with dates/moment

### ISSUE THREAD

**Issue by vooba** [visjs/vis-data#94]
vis-component: vis-data@6.3.5

The new dataset implementation of max/min does not work with dates/moments

A short example showing the issue:
`var dataset = new vis.DataSet();
var items = [{id : 1, date: moment("1995-12-25")}, {id : 2, date: moment("2000-12-25")}, {id : 3, date: moment("2019-12-25")}]
dataset.add(items)
dataset.max("date"); // returns null --> expected  {id : 3, date: moment("2019-12-25")}
dataset.max("id"); // returns  {id : 3, date: moment("2019-12-25")}
`

**Comment by Thomaash** [comment]
Hi @vooba,

the min and max functions are supposed to work with numbers. I don't think they have ever worked with dates or Moment. Plus all Moment functionality is deprecated and will be removed to prevent bundle bloat.

You should be able to achieve it using:
```typescript
const minItem: Item | null = dataset
  .stream()
  .min((date: Date): number => +date);

const maxItem: Item | null = dataset
  .stream()
  .max((date: Date): number => +date);

```

In similar fashion you can create Moment version or universal one for all kinds of dates.

**Comment by vooba** [comment]
Hi Thomaash,

thank you for the fast answer. 

The old "visjs"-dataset worked with dates too, but I will update my code to use the stream method.
